export const COLUMNS = [
  {
    title: '发票类型',
    width: 80,
    ellipsis: true,
    colKey: 'buyerInvoiceType',
    cell: { col: 'buyerInvoiceType' },
  },
  {
    title: '购方类型',
    width: 80,
    ellipsis: true,
    colKey: 'buyerType',
    cell: { col: 'buyerType' },
  },
  {
    title: '购方抬头',
    width: 200,
    ellipsis: true,
    colKey: 'buyerTitle',
    cell: { col: 'buyerTitle' },
  },
  {
    title: '购方税号',
    width: 200,
    ellipsis: true,
    colKey: 'buyerTaxNo',
    cell: { col: 'buyerTaxNo' },
  },
  {
    title: '状态',
    width: 80,
    ellipsis: true,
    colKey: 'state',
    cell: { col: 'state' },
  },
  {
    title: '开票金额',
    width: 120,
    ellipsis: true,
    colKey: 'money',
    cell: { col: 'money' },
  },
  {
    title: '提交时间',
    width: 200,
    ellipsis: true,
    colKey: 'createTime',
    cell: { col: 'createTime' },
  },
  {
    align: 'left',
    fixed: 'right',
    width: 100,
    colKey: 'op',
    title: '操作',
  },
];
