export const COLUMNS = [
  {
    title: '发票类型',
    width: 120,
    ellipsis: true,
    colKey: 'invoiceTypeCode',
    cell: { col: 'invoiceTypeCode' },
  },
  {
    title: '发票编号',
    width: 120,
    ellipsis: true,
    colKey: 'invoiceNo',
    cell: { col: 'invoiceNo' },
  },
  {
    title: '冲红发票编号',
    width: 120,
    ellipsis: true,
    colKey: 'redInvoiceNo',
    cell: { col: 'redInvoiceNo' },
  },
  {
    title: '购方类型',
    width: 80,
    ellipsis: true,
    colKey: 'buyerType',
    cell: { col: 'buyerType' },
  },
  {
    title: '购方抬头',
    width: 200,
    ellipsis: true,
    colKey: 'buyerTitle',
    cell: { col: 'buyerTitle' },
  },
  {
    title: '购方税号',
    width: 200,
    ellipsis: true,
    colKey: 'buyerTaxNo',
    cell: { col: 'buyerTaxNo' },
  },
  {
    title: '发票状态',
    width: 120,
    ellipsis: true,
    colKey: 'state',
    cell: { col: 'state' },
  },
  {
    title: '开票金额',
    width: 120,
    ellipsis: true,
    colKey: 'invoiceTotalPriceTax',
    cell: { col: 'invoiceTotalPriceTax' },
  },
  {
    title: '开票时间',
    width: 200,
    ellipsis: true,
    colKey: 'outTime',
    cell: { col: 'outTime' },
  },
  {
    align: 'left',
    fixed: 'right',
    width: 100,
    colKey: 'op',
    title: '操作',
  },
];
